name: 刷步数

on:
  workflow_dispatch:
  schedule:
   - cron: 0 9 * * *

  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0-rc.2
      - name: 开始
        run: |
          pip install requests
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          step='${{ secrets.STEP }}'
          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
      - name: 开始
        run: |
          time=$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')
          sed -i "s/^最近一次运行时间:.*/最近一次运行时间: $time （北京时间） /g" README.md